### PR TITLE
Changed String message type to CharSequence

### PR DESCRIPTION
**Pull request by LluisFelip**
I propose this change because in my App I need to use Spannable to have texts with different colors in the toasts. CharSequence seems a good parent of both String and Spannable and I think it's working fine.

By the way, thanks for this simple but nice lib! Congrats :)

### CODE REVIEW

**Comment by Shashank02051997** [comment]
Hi @LluisFelip thanks for the appreciation. I have checked your PR and seems to be correct. Before merge thinking of not to change the param on the current method but create one more method with character param what you say

**Comment by LluisFelip** [comment]
Wow! I was surprised to see this message, I did this more than a year ago hehe, I will review this later and update the PR to have it as a separated method 😄

**Comment by Shashank02051997** [comment]
If you want i can add two separate methods.

**Comment by LluisFelip** [comment]
If you can, that's great 👍

**Pull request closed without merging**
